# As noted in https://github.com/pypi/warehouse/issues/11096, the current
# version of PyPI's GitHub Actions workflow uses the repo which calls it for
# Trusted Publishing, meaning it doesn't support being called in a shared
# workflow.
# To use the common deploy workflow, copy the workflow below into your repo for
# direct use. If/when they fix it, we'll update ASAP.

name: Deploy to PyPI

on:
  workflow_call:

jobs:
  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
