name: PR

on:
  pull_request:

jobs:
  repo-checks:
    uses: ./.github/workflows/repo-checks.yml
    with:
      src: .github/actions
      check_deprecation: false

  tests:
    uses: ./.github/workflows/matrix-tests.yml
    with:
      src: .github/actions
      skip_38: true
      skip_39: true
      skip_310: true
